### ISSUE TITLE
Getting 404's on NPM

### ISSUE THREAD

**Issue by cawmit** [watson/raop-server#1]
I think something went wrong with submitting the package to NPM :)

**Comment by watson** [comment]
@TimWachter Sorry about that - I thought I would have a complete RAOP server finished right away, so I referenced npm too soon. I've updated the readme to show that it's not on npm yet and added links to two of my other modules that will serve as semi-replacements until I've finished this standalone RAOP module.

The two modules are:
- [raop-rtsp-server](https://github.com/watson/raop-rtsp-server) - for now a direct alternative to this module
- [rtsp-server](https://github.com/watson/rtsp-server) - a more low level implementation used to build the raop-rtsp-server module

I've realised that it might be hard to figure out which modules to use depending on what you like to achieve while it's still in so heavy early development, so I've made a gist that lists them all that I'll try and keep up to date: https://gist.github.com/watson/50e46a6085ffc805d326

**Comment by cawmit** [comment]
@watson Thanks for the reply. I look forward to seeing the completed project in the future!

**Comment by watson** [comment]
@TimWachter is there any features in a RAOP server that you are especially interested in?
